import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [
        '/api/',
        '/admin/',
        '/private/',
        '/_next/',
        '/podcasts/',
        '/cat/',
        '/cmat/',
        '/gmat/',
        '/iift/',
        '/mah-cet-mba/',
        '/mah-mba-cet/',
        '/mat/',
        '/nmat/',
        '/snap/',
        '/tancet/',
        '/tissnet/',
        '/xat/',
        '/ibps-clerk/',
        '/ibps-po/',
        '/ibps-so/',
        '/rbi-grade-b/',
        '/rrb-officer-scale-i/',
        '/sbi-clerk/',
        '/sbi-po/',
        '/sebi-grade-a/',
        '/ssc-cgl/',
        '/ssc-chsl/',
        '/ssc-cpo/',
        '/ssc-gd/',
        '/ssc-je/',
        '/ssc-jht/',
        '/ssc-mts/',
        '/ssc-selection-post/',
        '/ssc-stenographer/',
        '/rpf-constable/',
        '/rpf-si/',
        '/rrb-alp/',
        '/rrb-group-d/',
        '/rrb-je/',
        '/rrb-ntpc/',
        '/rrb-technician/',
        '/upsc-apfc/',
        '/upsc-capf-ac/',
        '/upsc-epfo/',
        '/gate/',
        '/ies/',
        '/psus/',
      ],
    },
    sitemap: 'https://prepbanker.com/sitemap.xml',
  };
}
