// PATH: app/terms/page.tsx
import type { Metadata } from 'next';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { Breadcrumb } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Terms & Conditions – PrepBanker',
  description: 'Read PrepBanker\'s Terms of Use and platform terms and conditions.',
  alternates: { canonical: 'https://prepbanker.com/terms' },
};

export default function TermsPage() {
  return (
    <>
      <Header />
      <main>
        {/* Hero Section */}
        <section style={{
          background: 'linear-gradient(135deg, var(--color-navy-deep), var(--color-navy-mid))',
          padding: '3rem 0',
        }}>
          <div className="container-custom">
            <Breadcrumb items={[{ label: 'Home', href: '/' }, { label: 'Terms & Conditions' }]} />
            <h1 style={{
              fontFamily: 'var(--font-display)',
              fontWeight: 800,
              fontSize: 'clamp(1.8rem, 4vw, 2.8rem)',
              color: '#fff',
              marginTop: '1.5rem',
            }}>
              Terms of <span className="text-gold-gradient">Use</span>
            </h1>
            <p style={{ color: 'rgba(255,255,255,0.6)', marginTop: '0.75rem' }}>
              PrepBanker Platform Terms and Conditions
            </p>
          </div>
        </section>

        {/* Content Section */}
        <section className="section-padding" style={{ background: '#fff' }}>
          <div className="container-custom" style={{ maxWidth: 780, color: 'var(--color-navy)', fontSize: '0.95rem', lineHeight: 1.8 }}>
            
            <p style={{ marginBottom: '1.5rem', color: 'var(--color-gray-650)' }}>
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>

            <p style={{ marginBottom: '1.5rem', color: 'var(--color-gray-650)' }}>
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name PrepBanker.com (&quot;https://prepbanker.com/&quot;), including the related mobile site and mobile application (hereinafter referred to as &quot;Platform&quot;).
            </p>

            <p style={{ marginBottom: '2.5rem', color: 'var(--color-gray-650)' }}>
              The Platform is owned by PrepBanker, a company incorporated under the Companies Act, 1956 with its registered office at PrepBanker (hereinafter referred to as &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
            </p>

            {/* Section: Agreement */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Agreement
              </h2>
              <p style={{ color: 'var(--color-gray-600)', marginBottom: '1rem' }}>
                Your use of the Platform and services and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable to the Platform for such transaction.
              </p>
              <p style={{ color: 'var(--color-gray-600)' }}>
                By mere use of the Platform, you shall be contracting with the Platform Owner and these terms and conditions including the policies constitute your binding obligations with the Platform Owner.
              </p>
            </div>

            {/* Section: Usage of Services */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Usage of Services
              </h2>
              <ul style={{ paddingLeft: '1.25rem', color: 'var(--color-gray-600)', listStyleType: 'disc', display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <li>You agree to provide true, accurate, and complete information during and after registration.</li>
                <li>You shall be responsible for all acts done through the use of your registered account.</li>
                <li>No warranty is provided as to the accuracy, timeliness, or completeness of the information on the Platform.</li>
                <li>Your use of the Platform is entirely at your own risk.</li>
                <li>The contents of the Platform are proprietary and licensed to us; unauthorized use may lead to legal action.</li>
              </ul>
            </div>

            {/* Section: Payments */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Payments
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                You agree to pay the charges associated with availing the Services.
              </p>
            </div>

            {/* Section: Prohibited Use */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Prohibited Use
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                You agree not to use the Platform for any unlawful or prohibited purposes.
              </p>
            </div>

            {/* Section: Third-Party Links */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Third-Party Links
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                The Platform may contain links to other third-party websites. Upon accessing these links, you will be governed by the terms and privacy policies of such websites.
              </p>
            </div>

            {/* Section: Contractual Obligations */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Contractual Obligations
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                Initiating a transaction for availing the Services constitutes a legally binding and enforceable contract with the Platform Owner.
              </p>
            </div>

            {/* Section: Indemnity */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Indemnity
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                You shall indemnify and hold harmless the Platform Owner and its affiliates from any claims or penalties arising out of your breach of these Terms.
              </p>
            </div>

            {/* Section: Limitation of Liability */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Limitation of Liability
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                In no event will the Platform Owner be liable for any indirect or consequential damages exceeding the amount paid by you for using the Services, or ₹100, whichever is less.
              </p>
            </div>

            {/* Section: Force Majeure */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Force Majeure
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                The parties shall not be liable for failure to perform obligations due to events beyond their control.
              </p>
            </div>

            {/* Section: Governing Law */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem', borderBottom: '1px solid var(--color-gray-100)' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Governing Law
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                These Terms shall be governed by the laws of India. All disputes will be subject to the exclusive jurisdiction of the courts in Nashik, Maharashtra.
              </p>
            </div>

            {/* Section: Contact Information */}
            <div style={{ marginBottom: '2rem', paddingBottom: '1.5rem' }}>
              <h2 style={{ fontWeight: 700, color: 'var(--color-navy)', fontSize: '1.25rem', marginBottom: '0.75rem' }}>
                Contact Information
              </h2>
              <p style={{ color: 'var(--color-gray-600)' }}>
                All concerns or communications relating to these Terms must be sent to us using the contact information provided on this website.
              </p>
            </div>

            {/* Copyright */}
            <p style={{ color: 'var(--color-gray-400)', fontSize: '0.85rem', borderTop: '1px solid var(--color-gray-100)', paddingTop: '1.5rem', marginTop: '2rem' }}>
              &copy; 2025 PrepBanker Technologies Pvt. Ltd. All rights reserved.
            </p>

          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}